### PR TITLE
adds support for Node standalone mode

### PR DESCRIPTION
**Pull request by wivern**
Related to OHDSI/ArachneNodeAPI#328

### CODE REVIEW

**Comment by wivern** [comment]
> 2. What is the reason for having `Model` column in DS list if it is always empty in Standalone mode?

It's not always empty. There is Achilles button In the stand-alone mode available regardless published or not.

**Comment by pavgra** [comment]
@wivern , Achilles button is located in a separate column - `ac-data-source-list-table__register-th`, while Model is in `...model-type-th`

**Comment by pavgra** [comment]
1. Columns width is not balanced
image

2. Tooltips shouldn't be shown if no text is presented

image

3. Tooltips are should show full text in the following cases
image

image

**Comment by pavgra** [comment]
Icons are not aligned. Let's use spacing as in the first line:
image

**Pull request merged**
